# run the mysql server and the web server (Dev)
version: "3.0"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "eupdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    
  
  # if you're working on the backend, comment this out and run it locally
  eup: # api
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: eup
    container_name: eup
    # ports:
    #   - "5000:5000"
    # volumes:
    #   - ./data/eup:/eup/www
    restart: always
    network_mode: host # not sure if this works on mac. specify full ip/port?

  # we'd want this stuff down the line
  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #   restart: always
  # redis:
  #   image: redis:5.0.5
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  # redis-server:
  #   image: redis